name: deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd linux-deployment
            git checkout main
            git pull origin main
            npm install
            npm run build
            
